pull_requests:
  - name: automatic merge when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=CI - Pull Request
      - base=master
    actions:
      merge:
        method: merge

pull_request_rules:
  - name: automatic merge for PyUp pull requests
    conditions:
      - author=pyup-bot
      - status-success=PyUp - Pull Request
    actions:
      merge:
        method: merge
