pull_request_rules:
  - name: automatic merge for PyUp pull requests
    conditions:
      - author=github-actions-bot
      - status-success=CI / build (pull_request)
    actions:
      merge:
        method: merge
