pull_request_rules:
  - name: automatic merge for PyUp pull requests
    conditions:
      - author=github-actions[bot]
      - status-success=Github Actions - Pull Request
    actions:
      merge:
        method: merge
