pull_request_rules:
  - name: automatic merge for PyUp pull requests
    conditions:
      - author=pyup-bot
      - status-success=<ci-name> - Pull Request
    actions:
      merge:
        method: merge
