pull_request_rules:
  - name: automatic merge for PyUp pull requests
    conditions:
      - author=pyup-bot
      - "status-success=ci/github-actions[bot]: my_testing_job"
    actions:
      merge:
        method: merge
